### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by emanom** [nstevens1040/PGPDecrypt-Message#1]
Hi, can you please advise what the passphrase is for your example?

**Comment by nstevens1040** [comment]
Hi, my apologies, I forgot to include the 'private_key_passphrase' parameter in the PGPDecrypt-Message example. Also, the PGP keys in the example expired about one week ago. I created a new PGP key and used it in the examples for both PGPDecrypt-Message and PGPEncrypt-Message. I also made sure to include the 'private_key_passphrase' parameter in the PGPDecrypt-Message example. Thank you.
